language: node_js
cache: npm
node_js:
  - 12
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
scripts:
  - npm install codecov -g
  - npm build
after_success:
  - codecov
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT