import _ from 'lodash';
import SwaggerParser from "swagger-parser";
import GeneratorApiModel from "./generatorApiModel";
import GeneratorApiPath from "./generatorApiPath";

// Used for file template generation
const ejs = require('ejs');

const path = require('path');
const fs = require('fs');

/**
 * Holds all API configuration that is read from a single definition file.
 * This file reads the definition and create API structure in code, that would be later 
 * generated into .ts files in your project.
 */
export default class GeneratorApiConfiguration {
    /**
     * Name of API from swagger definition.
     */
    private _name: string;

    /**
     * Path to swagger definition file.
     */
    private readonly _pathToDefinition: string;

    /**
     * Path to the folder that would contain all output files generated by this API definition.
     */
    private readonly _pathToOutputFolder: string;

    /**
     * The URL to the server that AXIOS should send requests to. This is used to define the axios client, create
     * one if it does not exist and use the name of the client in the actions functions to call action in
     * correct axios client.
     */
    private _serverUrl: string;

    /**
     * API request/result models used for transferring data via REST API.
     */
    private _models: GeneratorApiModel[];

    /**
     * Paths that are defined in the swagger file. Basically these are the endpoints on the remote server that
     * are accessed by action functions.
     */
    private _paths: GeneratorApiPath[];

    constructor(pathToDefinition: string, pathToBuild: string) {
        // Set default values
        this._pathToDefinition = pathToDefinition;
        this._pathToOutputFolder = pathToBuild;
        this._serverUrl = '';
        this._models = [];
        this._paths = [];
    }

    /**
     * Used to retrieve the name of the definition file. Is used to create a reducer and add a new axios client
     * whether it is required.
     */
    public getFileName(): string {
        return path.parse(this._pathToDefinition).name;
    }

    /**
     * Used by external Promise to create API structure. If something goes wrong it
     * calls reject function with error.
     * @param resolve Function called when method finishes successfully.
     * @param reject Function called when error occurs.
     */
    private createApiStructure = async (resolve, reject) => {
        try {
            const api: any = await SwaggerParser.validate(this._pathToDefinition);

            // Set all required models and create the structure of the API inside the code
            this._serverUrl = api.host + api.basePath;
            this._name = api.info.title;

            // Create models for API
            this._models = _.entries(api.definitions).map(def => {
                return new GeneratorApiModel(def[0], def[1]);
            });

            // Create paths from API object
            this._paths = _.entries(api.paths).map(def => {
                console.log(def);
                return new GeneratorApiPath(def[0], def[1]);
            });
        } catch (e) {
            reject(e);
        }

        resolve();
    };

    /**
     * Used by Promise to generate API files for this API configuration. If something goes wrong it
     * calls reject function with error.
     * @param resolve Function called when method finishes successfully.
     * @param reject Function called when error occurs.
     */
    private generateApiOutputs = (resolve, reject) => {
        try {
            let pathToActionsTemplate = path.resolve(__dirname, '../../src/templates/actions.ejs');
            let pathToModelsTemplate = path.resolve(__dirname, '../../src/templates/model.ejs');
            let pathToReducerTemplate = path.resolve(__dirname, '../../src/templates/reducer.ejs');
            let pathToModels = path.resolve(this._pathToOutputFolder, 'models');
            let pathToActions = path.resolve(this._pathToOutputFolder, 'actions');
            let pathToReducers = path.resolve(this._pathToOutputFolder, 'reducers');

            // Generate MODELS for every schema input in the api
            _.forEach(this._models, (model, index, arr) => {
                if (model.type === 'object') {
                    if (!fs.existsSync(pathToModels)) {
                        fs.mkdirSync(pathToModels, {recursive: true});
                    }
                    let renderedTemplate = ejs.render(fs.readFileSync(pathToModelsTemplate, 'utf8'), model);
                    fs.writeFileSync(path.resolve(pathToModels, model.name + '.ts'), renderedTemplate);
                }
            });

            // Generate actions for every path and method in the api file
            // Create the output folder if it does not exist
            if (!fs.existsSync(pathToActions)) {
                fs.mkdirSync(pathToActions, {recursive: true});
            }

            // Render the output file
            let renderedTemplate = ejs.render(
                fs.readFileSync(pathToActionsTemplate, 'utf8'), {_paths: this._paths});
            // Save the rendered actions file into the folder
            fs.writeFileSync(path.resolve(pathToActions, this._name + 'Actions.ts'), renderedTemplate);

            // Render the reducer file
            let reducerTemplate = ejs.render(
                fs.readFileSync(pathToReducerTemplate, 'utf8'), this);
            // Save the rendered reducer file into the folder
            fs.writeFileSync(path.resolve(pathToReducers, this._name + 'Reducer.ts'), renderedTemplate);
        } catch (e) {
            reject(e);
        }

        resolve();
    };

    /**
     * Creates this API with all required files.
     */
    public create(): Promise<any> {
        return new Promise(this.createApiStructure);
    }

    /**
     * Generate API files in the output directory.
     */
    public generate(): Promise<any> {
        return new Promise(this.generateApiOutputs);
    }
}
